%% Import data from text file.
% Script for importing data from the following text file:
%
%    /tmp/3dpoints_verify_distance3.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2017/05/09 14:21:45

% Initialize variables.
filename = '/tmp/3dpoints_verify_distance6.csv';
delimiter = ',';
startRow = 2;

% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: text (%s)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%s%f%f%f%[^\n\r]';

% Open the text file.
fileID = fopen(filename,'r');

% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

% Close the text file.
fclose(fileID);

% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

% Allocate imported array to column variable names
time = dataArray{:, 1};
fieldheaderseq = dataArray{:, 2};
fieldheaderstamp = dataArray{:, 3};
fieldheaderframe_id = dataArray{:, 4};
fieldpointx = dataArray{:, 5};
fieldpointy = dataArray{:, 6};
fieldpointz = dataArray{:, 7};


% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;


dist = sqrt((fieldpointx(1) - fieldpointx(2))^2 + (fieldpointy(1) - fieldpointy(2))^2 + (fieldpointz(1) - fieldpointz(2))^2)