# Path to be executed
geometry_msgs/Transform[] targets

# Speed (defined as the percentage of max speed, 0=no speed, 100=full speed in the leading axis)
float32[] speeds

# Blends of individual targets in percentage, 0=no blend, 100=full blend
float32[] blends

---
# If the service request was acknowledged
bool success
