set(_CATKIN_CURRENT_PACKAGE "ROVI2_Development")
set(ROVI2_Development_VERSION "0.0.0")
set(ROVI2_Development_MAINTAINER "mneerup <mneerup@todo.todo>")
set(ROVI2_Development_PACKAGE_FORMAT "1")
set(ROVI2_Development_BUILD_DEPENDS "roscpp" "std_msgs")
set(ROVI2_Development_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs")
set(ROVI2_Development_BUILDTOOL_DEPENDS "catkin")
set(ROVI2_Development_BUILDTOOL_EXPORT_DEPENDS )
set(ROVI2_Development_EXEC_DEPENDS "roscpp" "std_msgs")
set(ROVI2_Development_RUN_DEPENDS "roscpp" "std_msgs")
set(ROVI2_Development_TEST_DEPENDS )
set(ROVI2_Development_DOC_DEPENDS )
set(ROVI2_Development_DEPRECATED "")